import { Jost, Playfair_Display, Lato } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';

import Header from './components/Header';
import Footer from './components/Footer';

const jost = Jost({ subsets: ['latin'], variable: '--font-jost' });
const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  variable: '--font-lato',
});
const playfair = Playfair_Display({ subsets: ['latin'], variable: '--font-playfair' });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${jost.className} ${playfair.variable} ${lato.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
